{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.prometheus.serviceMonitor.name }}
  namespace: {{ .Values.namespace }}
  labels:
    monitoring: ns-{{ .Values.namespace }}
spec:
  jobLabel: {{ .Values.prometheus.serviceMonitor.jobName }}
  selector:
    matchLabels:
      monitor-{{ .Values.deployment.monitorApp.imageName }}: "true"
  namespaceSelector:
    matchNames:
    - {{ .Values.namespace }}      
  endpoints:
  - port: web
    interval: {{ .Values.prometheus.serviceMonitor.scrapInterval }}
    path: {{ .Values.prometheus.serviceMonitor.scrapPath }}
{{- end }}      